name: Windows builds
permissions: read-all

on:
  push:
    paths-ignore:
      - '.clang-format'
      - '.mdl-styles'
      - '*.md'
      - 'docs/**'
      - 'licenses/**'
      - 'website/**'

  pull_request:
    paths-ignore:
      - '.clang-format'
      - '.mdl-styles'
      - '*.md'
      - 'docs/**'
      - 'licenses/**'
      - 'website/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VCPKG_ROOT: C:\vcpkg
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build_windows_vs:
    name: ${{ matrix.conf.name }}
    runs-on: windows-2019
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        conf:
          - name: MS Clang/LLVM (x64)
            arch: x64
            max_warnings: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Checkout vcpkg baseline
        shell: pwsh
        run: |
          $baseline = (Get-Content vcpkg.json | ConvertFrom-Json).'builtin-baseline'
          cd $env:VCPKG_INSTALLATION_ROOT
          git fetch
          rm vcpkg.exe
          git -c advice.detachedHead=false checkout $baseline
          bootstrap-vcpkg.bat -disableMetrics

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Setup VS dev cmd
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup CMake
        uses: lukka/get-cmake@v4.0.1

      - name: Install vcpkg packages
        run: vcpkg install

      - name: Print VCPKG error log
        if: failure()
        shell: pwsh
        run: Get-Content -Path vcpkg_installed/${{ matrix.conf.arch }}-windows/vcpkg/issue_body.md

      - name: Export vcpkg packages
        run: vcpkg export --raw --output-dir=.

      - name: Upload vcpkg export
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-export-${{ matrix.conf.arch }}-windows
          path: vcpkg-export-*
  